### ISSUE TITLE
Modified use case - getting error while executing script

### ISSUE THREAD

**Issue by anoopdi** [MediaIQ/aws-utils#11]
I have a requirement to scan a particular JSON file from the S3 bucket. The bucket has 1000s of folders and each of those folders has subfolders and a file named receipt.json.  The following is the structure. 
```
bucket
      ----- folder
              ----- subfolder
              ----- receipt.json
```

The subfolders have multiple files which I do not want to query, with a slight modification to your s3_executor script, I was able to get the script to only check receipt.json 

        for obj in contents:
            key = obj['Key']
            **if  key.startswith(prefix) and key.endswith("receipt.json"):**

When I run the script with a simple SQL query like `SELECT * FROM s3object s` , the script is scanning the receipt.json files and prints output to the console. However, if I modify the SQL query to filter the fields, i get the following error message

SQL - SELECT * FROM s3object[*].manifest s

Error

Performing, with:  anr-cribl-data smartstore/cribl_json/db/03/bd/3~19F003DD-45C9-45AC-A3EC-C640F4A52D5A/receipt.json SELECT * FROM s3object[*].manifest s None CSV {'AllowQuotedRecordDelimiter': True, 'QuoteCharacter': '', 'FieldDelimiter': ','}
Traceback (most recent call last):
  File "s3_executor.py", line 165, in <module>
    perform(bucket, item, sql, comp, content_type, content_options, output_file)
  File "/mnt/c/Users/anoop/Documents/query_s3/select_runner.py", line 73, in perform
    r = s3.select_object_content(
  File "/home/anoop/.local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anoop/.local/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidDataSource) when calling the SelectObjectContent operation: Data source type path is not supported. Please check the service documentation and try again.
I have attached the a sample of the json file i am querying.

Any help on this is really appreciated.

[sample.txt](https://github.com/miqdigital/aws-utils/files/6013567/sample.txt)

**Comment by ntantri** [comment]
@anoopdi can you provide the full python command you are trying to execute?

**Comment by anoopdi** [comment]
@tan31989 
This one works for me
`python3 s3_executor.py -b "anr-cribl-data" -p "smartstore/cribl_json/db" -c JSON -s "SELECT * FROM s3object s" -comp None -d COMMA`
this one doesn't
`python3 s3_executor.py -b "anr-cribl-data" -p "smartstore/cribl_json/db" -c JSON -s "SELECT * FROM s3object[*].manifest s" -comp None -d COMMA`

**Comment by ntantri** [comment]
@anoopdi will test this and update you over the same.

**Comment by ntantri** [comment]
@anoopdi can you check once? I have modified it to have JSON as a separate argument and now the following query should work:

`python3 s3_executor.py -b bucket -p 'sample.json' -c JSON -s "SELECT * FROM s3object[*].manifest s" -comp None -d None`

**Comment by anoopdi** [comment]
The updated code works like a charm!. Thank you so much for looking into this. @tan31989
