### ISSUE TITLE
str() issue and wiki page fix

### ISSUE THREAD

**Issue by alanbuxey** [MediaIQ/aws-utils#2]
hi, an interesting and useful tool to use with s3 select (the main issue with the native awscli is lack of directory support!). however, the str() function is problematic with non-ascii characters and a system not with correct locale (locally I've fixed that by settings UTF-8 for the sys.  the general suggestion is to use .encode() 

also, for the wiki entry that led me here: https://medium.com/miq-tech/https-medium-com-nagaraj-mediaiq-how-we-use-s3-select-for-schema-validation-and-filtering-data-at-miq-52cf036bf9be .  - the file is select_runner.py, not s3_runner.py . (minor issue but might throw people...)

cheers!

**Comment by ntantri** [comment]
Hi @alanbuxey ,

Thank you for notifying us about the changes to make.
Is it possible for you raise a PR in this case for a fix?

As well thanks for reading the blog, will change the name in the blog to reflect: select_runner.py

Appreciate your help on this.

Regards,
Nagaraj
